// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJqKfJ5CQSeW-4JUiZ_4HWZuc74cryI_E',
    appId: '1:936138241304:web:36a54e3cb3232fc534da6d',
    messagingSenderId: '936138241304',
    projectId: 'flutterbcaapp',
    authDomain: 'flutterbcaapp.firebaseapp.com',
    storageBucket: 'flutterbcaapp.firebasestorage.app',
    measurementId: 'G-DDY2814NPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTBV2nUjiXtyMG2wrnU2RwOhdOqQsFr44',
    appId: '1:936138241304:android:7b8478a9147a717b34da6d',
    messagingSenderId: '936138241304',
    projectId: 'flutterbcaapp',
    storageBucket: 'flutterbcaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo498_Ubl2PDH9YomIrwdgTtNyWMa8sDU',
    appId: '1:936138241304:ios:cf344fc3078be01034da6d',
    messagingSenderId: '936138241304',
    projectId: 'flutterbcaapp',
    storageBucket: 'flutterbcaapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterBcaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo498_Ubl2PDH9YomIrwdgTtNyWMa8sDU',
    appId: '1:936138241304:ios:cf344fc3078be01034da6d',
    messagingSenderId: '936138241304',
    projectId: 'flutterbcaapp',
    storageBucket: 'flutterbcaapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterBcaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJqKfJ5CQSeW-4JUiZ_4HWZuc74cryI_E',
    appId: '1:936138241304:web:b92ad3d830b8802f34da6d',
    messagingSenderId: '936138241304',
    projectId: 'flutterbcaapp',
    authDomain: 'flutterbcaapp.firebaseapp.com',
    storageBucket: 'flutterbcaapp.firebasestorage.app',
    measurementId: 'G-YBFJCWPXN2',
  );
}
